apiVersion: v1
kind: pod 
metadata:
  name: pod-configmaps

spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: joindevops
            key: course
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: joindevops
            key: trainer