apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

managedNodeGroups:
  - name: expence
    instanceType: m5.large
    desiredCapacity: 3
    spot : true


# to delete cluster --> eksctl delete cluster --config-file=eks.yaml
# to create cluster --> eksctl create cluster --config-file=eks.yaml