apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: ebs-static

spec: 
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 100Gi
  csi: 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-071b27f852a50e4d4
---
apiVersion: v1 
kind: PersistentVolumClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" #empty string must be explicitly set otherwise default storageclass
  volumeName: ebs-static
  accessModes:
  - ReadWriteOnce
  resources:  
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: pod 
metadata:
  name: nginx-static
  labels:
    purpose: ebs-static
    project: expence
spec: 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistant-storage
      mountPath: /usr/share/nginx/html
  volume:
  - name: persistant-storage
    persistantVolumeClaim: 
      claimName: ebs-static
---
kind: service
apiVersion: v1 
metadata:
  name: nginx-static
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
    project: expence
  ports:
  - protocol: TCP
    port: 80 # service port (load-balancer)
    targetport: 80  #target port  
    NodePort: 32761