kind: Deployment 
apiVersion: apps/v1
metadata:
  name: app-1
  #these lables are deployment related lables
  lables:
    app: nginx
    purpose: ingresss
    
spec:
    selector:
      matchlables:
        app: nginx
        purpose: ingresss
    template:
      metadata:
        lables:
          app: nginx
          purpose: ingresss
        spec:
          containers:
          - name: ngapp-1
            image: joindevops/app1:1.0
---
apiVersion: v1 
kind: service 
metadata:
  name: app-1
spec:
  selector:
      app: nginx
      purpose: ingresssv

  ports:
  - protocol: TCP
    port: 80 # service port (load-balancer)
    targetport: 80  #target port 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "app1.devops-project.site" #ALB rule
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-1 #ALB target group
            port:
              number: 80